services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: server
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    networks:
      - custom_network
    depends_on:
      - db
  db:
    image: mysql:5.7
    container_name: db
    restart: always
    environment:
      MYSQL_DATABASE: 'lojavirtual'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - "3306:3306"
    volumes:
      - './.docker/mysql/data:/var/lib/mysql'
      - './.docker/mysql/dump:/docker-entrypoint-initdb.d'
    networks:
      - custom_network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - 8001:80
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    networks:
      - custom_network
networks:
  custom_network:
    driver: bridge 